"""add column name

Revision ID: 955a6d5482ac
Revises: 0b46d17d5fec
Create Date: 2024-07-05 11:42:27.089357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955a6d5482ac'
down_revision = '0b46d17d5fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
